package sc.snicky.oms.domain.exceptions.codes;

public enum OrderErrorCode {
    ORDER_NOT_FOUND,
    ORDER_CREATION_FAILED,

    ORDER_NUMBER_INVALID_LENGTH,
    ORDER_NUMBER_EMPTY_OR_NULL,

    ORDER_STATUS_INVALID_TRANSITION,

    ORDER_ID_EMPTY_OR_NULL,

    CUSTOMER_ID_EMPTY_OR_NULL,
    CUSTOMER_ID_INVALID_LENGTH
}
